site_name: Sage Documentation Site
pages:
- ['index.md', 'Home']
- ['getting_started.md', 'Overview', 'Getting Started']
- ['cm_circulation_brief.md', 'Overview', 'Circulation Overview']
- ['catm_cataloging_brief.md', 'Overview', 'Cataloging Overview']
- ['circulation_module.md', 'Core Modules', 'Circulation']
- ['cataloging_module.md', 'Core Modules', 'Cataloging']
- ['opac.md', 'Core Modules', 'OPAC']
- ['administration.md', 'Core Modules','Administration']
- ['cat_materials_migrated.md', 'Migrated Materials', 'Cataloging Materials - Sage Wiki']
- ['contact_info.md', 'Miscellaneous', 'Library Contact Information']
- ['circ_hold_policies.md', 'Miscellaneous', 'Backend Configurations']
- ['contribute.md', 'Miscellaneous', 'Contributions: How-To']

markdown_extensions: [admonition]
theme: readthedocs