site_name: Sage Documentation Site
pages:
- ['index.md', 'Home']

- ['overview/getting_started.md', 'Overview', 'Getting Started']
- ['overview/cm_circulation_brief.md', 'Overview', 'Circulation Overview']
- ['overview/catm_cataloging_brief.md', 'Overview', 'Cataloging Overview']
- ['overview/patron_faq.md', 'Overview', 'Patron FAQs']
- ['overview/install.md', 'Overview', 'Evergreen Installation']

- ['core-modules/circulation_module.md', 'Core Modules', 'Circulation']
- ['core-modules/cataloging_module.md', 'Core Modules', 'Cataloging']
- ['core-modules/opac.md', 'Core Modules', 'OPAC']
- ['core-modules/administration.md', 'Core Modules','Administration']

- ['misc/contact_info.md', 'Miscellaneous', 'Library Contact Information']
- ['misc/downloads.md', 'Miscellaneous', 'Downloadable Documentation']
- ['misc/courier.md', 'Miscellaneous', 'Courier Information']
- ['misc/circ_hold_policies.md', 'Miscellaneous', 'Backend Configurations']
- ['misc/contribute.md', 'Miscellaneous', 'Contributions (How-To)']

extra_javascript: [external_links.js]

theme: 'readthedocs'
